static const char black[]       = "#303446";
static const char gray2[]       = "#303446"; // unfocused window border
static const char gray3[]       = "#545862";
static const char gray4[]       = "#949CBB";
static const char blue[]        = "#8CAAEE"; // focused window border
static const char green[]       = "#A6D189";
static const char red[]         = "#E78284";
static const char orange[]      = "#EF9F76";
static const char yellow[]      = "#E5C890";
static const char pink[]        = "#EA999C";
static const char purple[]      = "#CA9EE6";
static const char cyan[]        = "#81C8BE";
static const char col_borderbar[]  = "#303446"; // inner border
